kind: pipeline
name: default

steps:
  - name: lint-infra
    image: hashicorp/terraform
    commands:
      - terraform fmt --check infra || { echo -e "\n^ The above files could use some 'terraform fmt' love" >&2; exit 1; }
    when:
      event:
        - pull_request

  # TODO: consider deploying to a staging environment, and await promotion to deploy to prod.
  - name: publish-legal
    image: plugins/s3-sync:1
    settings:
      bucket: osv-im-us-west-2-legal-assets
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-west-2
      source: legal
      delete: true
      cloudfront_distribution: E1GIXA14V6CST6
    when:
      event:
        - pull_request
      branch:
        - master
