kind: pipeline
name: default

steps:
  - name: lint-infra
    image: hashicorp/terraform
    commands:
      - terraform fmt --check infra || { echo -e "\n^ The above files could use some 'terraform fmt' love" >&2; exit 1; }
    when:
      event:
        - pull_request

  - name: publish-legal
    image: plugins/s3-sync:1
    settings:
      bucket: osv-im-us-west-2-legal-assets
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-west-2
      source: legal
      delete: true
      cloudfront_distribution: E1GIXA14V6CST6
    when:
      event:
        - push
      branch:
        - master

  - name: publish-globetheater
    image: plugins/s3-sync:1
    settings:
      bucket: osv-im-us-west-2-globetheater-assets
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-west-2
      source: globetheater
      delete: true
      cloudfront_distribution: E125YIYAMJVUWR
    when:
      event:
        - push
      branch:
        - master
  
  - name: generate-root
    image: node
    commands:
      - npm install -g yarn
      - cd root && yarn && make generate
    when:
      event:
        - push
      branch:
        - master

  - name: publish-root
    image: plugins/s3-sync:1
    settings:
      bucket: osv-im-us-west-2-root-assets
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-west-2
      source: root/dist
      delete: true
      cloudfront_distribution: E1ZAUILNHKOJ6B
      cache_control:
        "*.png": "public, max-age: 31536000"
        "*.jpg": "public, max-age: 31536000"
        "*.js": "public, max-age: 31536000"
    when:
      event:
        - push
      branch:
        - master
